version: "3"

services:
  customer-service:
    image: rfcardoso07/customer-service:1.0
    depends_on:
      - customer-database
    ports:
      - "8080:8080"
    networks:
      - app-net
    env_file:
      - customer-service/.env
    environment:
      - GIN_MODE=${MODE}
      - APPLICATION_AUTH_PATTERN=${PATTERN}

  customer-database:
    image: postgres:11.4
    ports:
      - "8081:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  account-service:
    image: rfcardoso07/account-service:1.0
    depends_on:
      - account-database
    ports:
      - "8082:8082"
    networks:
      - app-net
    env_file:
      - account-service/.env
    environment:
      - GIN_MODE=${MODE}
      - APPLICATION_AUTH_PATTERN=${PATTERN}

  account-database:
    image: postgres:11.4
    ports:
      - "8083:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  transaction-service:
    image: rfcardoso07/transaction-service:1.1
    depends_on:
      - transaction-database
    ports:
      - "8084:8084"
    networks:
      - app-net
    env_file:
      - transaction-service/.env
    environment:
      - GIN_MODE=${MODE}
      - APPLICATION_AUTH_PATTERN=${PATTERN}

  transaction-database:
    image: postgres:11.4
    ports:
      - "8085:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  notification-service:
    image: rfcardoso07/notification-service:1.0
    depends_on:
      - notification-database
    ports:
      - "8086:8086"
    networks:
      - app-net
    env_file:
      - notification-service/.env
    environment:
      - GIN_MODE=${MODE}
      - APPLICATION_AUTH_PATTERN=${PATTERN}

  notification-database:
    image: postgres:11.4
    ports:
      - "8087:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  balance-service:
    image: rfcardoso07/balance-service:1.0
    depends_on:
      - balance-database
    ports:
      - "8088:8088"
    networks:
      - app-net
    env_file:
      - balance-service/.env
    environment:
      - GIN_MODE=${MODE}
      - APPLICATION_AUTH_PATTERN=${PATTERN}

  balance-database:
    image: postgres:11.4
    ports:
      - "8089:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  auth-service:
    image: rfcardoso07/auth-service:1.0
    depends_on:
      - auth-database
    ports:
      - "8090:8090"
    networks:
      - app-net
    env_file:
      - auth-service/.env
    environment:
      - GIN_MODE=${MODE}

  auth-database:
    image: postgres:11.4
    ports:
      - "8091:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  gateway:
    image: rfcardoso07/gateway:1.1
    depends_on:
      - customer-service
      - account-service
      - transaction-service
      - notification-service
    ports:
      - "8000:8000"
    networks:
      - app-net
    env_file:
      - gateway/.env
    environment:
      - GIN_MODE=${MODE}
      - GATEWAY_AUTH=${EDGE_AUTH}

networks:
  app-net: