version: "3"

services:
  customer-service:
    build: ./customer-service
    depends_on:
      - customer-database
    ports:
      - "8080:8080"
    networks:
      - app-net
    env_file:
      - customer-service/.env

  customer-database:
    image: postgres:11.4
    ports:
      - "8081:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  account-service:
    build: ./account-service
    depends_on:
      - account-database
    ports:
      - "8082:8082"
    networks:
      - app-net
    env_file:
      - account-service/.env

  account-database:
    image: postgres:11.4
    ports:
      - "8083:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  transaction-service:
    build: ./transaction-service
    depends_on:
      - transaction-database
    ports:
      - "8084:8084"
    networks:
      - app-net
    env_file:
      - transaction-service/.env

  transaction-database:
    image: postgres:11.4
    ports:
      - "8085:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  notification-service:
    build: ./notification-service
    depends_on:
      - notification-database
    ports:
      - "8086:8086"
    networks:
      - app-net
    env_file:
      - notification-service/.env

  notification-database:
    image: postgres:11.4
    ports:
      - "8087:5432"
    networks:
      - app-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  balance-service:
    build: ./balance-service
    depends_on:
      - balance-database
    ports:
      - "8088:8088"
    env_file:
      - balance-service/.env

  balance-database:
    image: postgres:11.4
    ports:
      - "8089:5432"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  auth-service:
    build: ./auth-service
    depends_on:
      - auth-database
    ports:
      - "8090:8090"
    env_file:
      - auth-service/.env

  auth-database:
    image: postgres:11.4
    ports:
      - "8091:5432"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  gateway:
    build: ./gateway
    depends_on:
      - customer-service
      - account-service
      - transaction-service
      - notification-service
    ports:
      - "8000:8000"
    networks:
      - app-net
    env_file:
      - gateway/.env

networks:
  app-net: