apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: account-database
spec:
  selector:
    app: account-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432