apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-database
spec:
  selector:
    app: auth-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432