apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: rfcardoso07/auth-service:1.0
        ports:
        - containerPort: 8090
        env:
        - name: AUTH_SERVICE_DATABASE_HOST
          value: "auth-database"
        - name: AUTH_SERVICE_DATABASE_PORT
          value: "5432"
        - name: AUTH_SERVICE_DATABASE_USER
          value: "admin"
        - name: AUTH_SERVICE_DATABASE_PASSWORD
          value: "admin"
        - name: AUTH_SERVICE_DATABASE_NAME
          value: "admin"
        - name: GIN_MODE
          value: "release"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-database
  template:
    metadata:
      labels:
        app: auth-database
    spec:
      containers:
      - name: auth-database
        image: postgres:11.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"