apiVersion: v1
kind: Service
metadata:
  name: balance-service
spec:
  selector:
    app: balance-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: balance-database
spec:
  selector:
    app: balance-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432