apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: customer-database
spec:
  selector:
    app: customer-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432