apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: account-database
spec:
  selector:
    app: account-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432