apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: rfcardoso07/notification-service:1.0
        ports:
        - containerPort: 8086
        env:
        - name: NOTIFICATION_SERVICE_DATABASE_HOST
          value: "notification-database"
        - name: NOTIFICATION_SERVICE_DATABASE_PORT
          value: "5432"
        - name: NOTIFICATION_SERVICE_DATABASE_USER
          value: "admin"
        - name: NOTIFICATION_SERVICE_DATABASE_PASSWORD
          value: "admin"
        - name: NOTIFICATION_SERVICE_DATABASE_NAME
          value: "admin"
        - name: CUSTOMER_SERVICE_HOST_AND_PORT
          value: "customer-service:8080"
        - name: ACCOUNT_SERVICE_HOST_AND_PORT
          value: "account-service:8082"
        - name: AUTH_SERVICE_HOST_AND_PORT
          value: "auth-service:8090"
        - name: GIN_MODE
          value: "release"
        - name: APPLICATION_AUTH_PATTERN
          value: "NO_AUTH"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-database
  template:
    metadata:
      labels:
        app: notification-database
    spec:
      containers:
      - name: notification-database
        image: postgres:11.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"