version: "3"

services:
  account-database:
    image: postgres:11.4
    ports:
      - "8101:5432"
    networks:
      - account-net
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  account-service:
    build: .
    depends_on:
      - account-database
    ports:
      - "8001:8001"
    networks:
      - account-net
    env_file:
      - .env

networks:
  account-net: