version: "3"

services:
  account-service:
    build: .
    depends_on:
      - account-database
    ports:
      - "8082:8082"
    env_file:
      - .env

  account-database:
    image: postgres:11.4
    ports:
      - "8083:5432"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin