version: "3"

services:
  customer-service:
    build: .
    depends_on:
      - customer-database
    ports:
      - "8080:8080"
    env_file:
      - .env

  customer-database:
    image: postgres:11.4
    ports:
      - "8081:5432"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin