version: "3"

services:
  customer-database:
    image: postgres:11.4
    ports:
      - "5432:5432"
    network_mode: host
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres.local:5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  customer-service:
    build: .
    depends_on:
      - customer-database
    ports:
      - "8000:8000"
    network_mode: host
    env_file:
      - .env